### ISSUE TITLE
Zeolite SMARTS strings?

### ISSUE THREAD

**Issue by erjank** [jennyfothergill/UFF-foyer#1]
HOW TO?

**Comment by jennyfothergill** [comment]
right now, I'm doing it by selecting any oxygen with 2 bonds which is bonded to Al,Si,Ti,Sn, or Zn:
`<Type name="O_3_z" class="O_3_z" element="O"  mass="15.9994" def="[O;X2]([Al,Si,Ti,Sn,Zn])" overrides="O_, O_3" desc="zeolite oxygen"/> `
Seems to work! In my current test it only fails for atoms on edge of pbc #3
